### ISSUE TITLE
jmespath.spec?

### ISSUE THREAD

**Issue by mtdowling** [jmespath/jmespath.test#1]
It's hard right now to submit a proposed change to jmespath because I need to send a PR to jmespath.test then one to boto/jmespath. I suggest moving the spec, docs, and test cases to jmespath.spec (or something similar) so that language proposals, new functions, etc can be managed in a single place.

**Comment by mtdowling** [comment]
I think making a `jmespath/jmespath` repo that combines `jmespath.test` and `jmespath.site` would be great to help contributors be able to more easily add test cases, documentation, and proposals in a single PR. What do you think, @jamesls?

**Comment by jamesls** [comment]
I'd be interested in having a repo that contains just the proposals, and maybe the spec as well.

I'd like to make it easier for people to propose ideas, and not necessarily require them to have to update the specification or add test cases.

I've seen that languages such as go and rust have repos just for proposals, I'm wondering if maybe a jmespath.jep makes sense here.  What's most important is the proposal and the discussion around the proposal.  Once it's been approved, in theory anyone can update the spec or add test cases (though it's great if the proposer also wants to take on that work).  Otherwise, it's potentially wasted effort if a user updates the spec and add tests for a proposal that's rejected.

What do you think?

**Comment by mtdowling** [comment]
Sure that sounds good. When I submit JEPs, I could just open two separate pull requests if needed -- one for the spec and one for the tests.

**Comment by jamesls** [comment]
Closing out old issue, there's now a jmespath.jep repo for new language features, where tests are added directly to the JEP.
